### PR TITLE
Fix remotipart for current rails ujs implementation

### PR DESCRIPTION
**Pull request by shwoodard**
Hi Guys,

Did a little tlc on your form plugin.  Looks nice, but there were a few gramatical improvements that I made as well as whitespace cleanup, all in separate commits of course.   Also, I made it work with the new rails ujs. :)

Hope this helps,
Sam

### CODE REVIEW

**Comment by JangoSteve** [comment]
Hey Sam, thanks for this! Is there any chance I could get you to break these changes into a couple different pull requests? I like the first 2 commits for not waiting for DOM load and fixing the whitespace, so I'd like to pull those in.

Concerning [9d85c98](https://github.com/wildfireapp/remotipart/commit/9d85c9831b9906e27787557ac4221fb04d6cedb9), I'd like to leave the `else` block in, since it doesn't hurt and it also mimics the jquery-ujs method that it's rewriting. The idea is to keep the `callRemote()` function as close to the method it overwrites (well, the one it did overwrite anyway), to make it as clear as possible what actually changed. I.e. if someone does a diff between the two methods, the diff should be as small as possible.

Concerning [4d2a8cc](https://github.com/wildfireapp/remotipart/commit/4d2a8cc89b36285705fb9da4b5fbae052bef5fe9), I've started making changes to the gem such that we can still be backwards-compatible with the old jquery-ujs as well. If you want to submit this as a separate pull request, I can combine it with my gem changes. 

However, be aware that I also have a complete rewrite of the remotipart.js which will work with the next version of the jquery-ujs. As soon as [this pull request](https://github.com/rails/jquery-ujs/pull/96) and [this one](https://github.com/rails/jquery-ujs/pull/87) are pulled into jquery-ujs, I have a complete rewrite ready that's only about 30 lines long.

**Comment by shwoodard** [comment]
Unfortunately, the whitespace and dom ready commits were actually the last two commits, so they will not cherry-pick to a different branch easily.

Good luck with your rewrite.  I will use our fork for now until you're ready.

Cheers,
Sam

**Comment by shwoodard** [comment]
Btw, I have to disagree with you about the `else` bit, regardless of the pattern you are trying to mimic,

```
if (foo) {
   raise 'blah';
} else {
    // do something
}
```

is pretty silly. ;)

**Comment by JangoSteve** [comment]
Oh, I didn't say it wasn't silly :-) 

I'm just saying 

a) it has no adverse effects, and 

b) that's how it was in the latest supported version of the jquery-ujs. 

If a less-experienced developer were trying to modify remotipart.js, and they were comparing it side-by-side with the jquery-ujs to gain a better understanding of how it works (a common scenario to be sure), it could potentially confuse them, as they sit there wondering why the `else` had to be removed in order to make ajax file uploads work. 

By leaving in a bit of harmless code, we can potentially save someone half an hour of pulling their hair out trying to understand the remotipart.js.

**Comment by shwoodard** [comment]
fair enough. i have another pull request for you, i think your going to like this one.  sec.

**Comment by JangoSteve** [comment]
Oh, I see, I had read the commit order backwards, my bad. The [22ef70b](https://github.com/wildfireapp/remotipart/commit/22ef70b59a180a42d7700db1990e2596ae9468c5) should cherry-pick ok. Could you do that as one pull and the other three as a single pull request?

**Comment by shwoodard** [comment]
Let's get the missing comma bit (subsequent pull request) merged in, and then I'll do these other two.  cool?

**Comment by shwoodard** [comment]
Can we close this pull request in light of the other pull request and the other individual ones that I will create, per your request?

**Pull request closed without merging**
