### PR TITLE
iFrameTransport and DataType

### PR DESCRIPTION
**Pull request by ajrkerr**
Hey Steve,

Took a bit longer than I had anticipated to make the changes.  I've also modified iFrameTransport a bit and submitted a pull request, though they have not yet replied.

Summary of Changes:
- Used jQuery.iFrameTransport instead of jQuery.Forms
- Had it dynamically pull the dataType that is sent to jQuery and put it in a hidden field (X-Html-Accept)
- Put a Rack Middleware together that grabs that, and the iFrame field and modifies the associated variables
- Put an override together for ActionController.render to package the response in a <textarea>
- Updated Railties and Engine to match
- Updated remotipart.js to autoinclude it's dependency (for Rails 3.1)
- Adam

### CODE REVIEW

**Comment by JangoSteve** [comment]
Wow, this is awesome. Give me a few days to look through this and thoroughly test it and whatnot. Thanks, Adam!

**Comment by ajrkerr** [comment]
Oh yeah.  I've been using Rails 3.1 primarily, and truth be told haven't really tried it in Rails 3.0.  Hope it works well.

**Comment by gucki** [comment]
I just tried it with chrome:
1. The submission/ upload seems to work fine without any problems.
2. However the response is empty (with current remotipart I get back the contents of my create.js view).

**Comment by ajrkerr** [comment]
I'll give it a look over.  What version of Rails are you using?

**Comment by gucki** [comment]
@ajrkerr I tried with rails 3.1.0rc4 and 3.1 stable branch. Thanks :-)

@leppert What about the idea to embed a tiny rails3 installation for integration tests with selenium?

**Comment by ajrkerr** [comment]
Hmm... Working fine for me in 3.1rc5 (I had to use rc5 because the asset pipeline wasn't working in rc4 properly, the issue tracker mentioned something about a sprockets update breaking it).

https://github.com/ajrkerr/testapp

Using the inspect tool for Chrome doesn't show any content being returned, however jQuery will still pick it up.

**Comment by JangoSteve** [comment]
@gucki, I've been wanting to do a Rails app with integration tests for quite a while now. The demo app is done, I just haven't gotten around to spending the hour or so to outfit it with integration specs.
- [Rails 3.1 Demo with Remotipart](https://github.com/JangoSteve/Rails-jQuery-Demo/tree/remotipart)
- [Rails 3.0 Demo with Remotipart](https://github.com/JangoSteve/Rails-jQuery-Demo/tree/remotipart-rails-3-0)

I was actually planning to finally write the spec suite and use it to test this pull request, which is the reason it's taken a while (I've been backed up with client stuff and haven't had a chance to do this yet).

@ajrkerr, there shouldn't be any problems with 3.1.rc4, as remotipart was working fine with it. If something in this update broke 3.1.rc4, I'd like to know what it is exactly before deciding whether or not it matters.

**Comment by ajrkerr** [comment]
@JangoSteve My apologies, I didn't mean to imply that there was something broken with Remotipart and RC4.  The incompatibility is between Rails RC4 and Sprockets beta10.  Simply, the assets aren't being routed properly with that combination.

We're doing development using RC4 and Chrome, and it hasn't given us any issues (at least with how we have things rigged together).  That test app was one tossed together really quickly to ensure that it would work off a fresh rails app.

**Comment by JangoSteve** [comment]
I understand the issues with Rails rc4 / Sprockets beta10. My point was that the 3.1 demo linked above was using rc4/beta10, and remotipart worked fine. If something in this pull request actually makes the rc4/beta10 conflict relevant to remotipart (which it wasn't before), I'd like to know what it is.

Are you saying that this pull request works fine with rc4/beta10, and that the conflict was only because of stuff that was rigged together in your particular app?

**Comment by gucki** [comment]
@ajrkerr I upgraded my app to rails 3.1.0.rc5 with remotipart from your master branch. It still does not work. In firefox using firefox I can see the response:

```
<textarea data-type="text/html"><textarea id="remotipart_response" name="remotipart_response">close_dialog();&#x000A;redirect_to(&quot;/de/companies/22/images&quot;)&#x000A;</textarea>
</textarea>`
```

Somehow there seem to be two textarea tags and too much escaping going on.

**Comment by ajrkerr** [comment]
@gucki  Oh, I see now.  My patch removes the requirement to wrap a textarea around your JS in the views, but leaves the helper in.  The outer one is from the override to the Render method and the inner one is from calling the remotipart_response method (which as far as I recall is manual).  Try removing any calls to remotipart_response and trying again.

**Comment by ajrkerr** [comment]
@JangoSteve The issue I was experiencing with that particular setup was that none of the JS was being pulled down, and this was independent of having remotipart installed.  See: https://github.com/rails/rails/issues/1810

**Comment by JangoSteve** [comment]
@ajrkerr, could you keep the `remotipart_response` helper so that it doesn't break apps that have it, but then just remove the textarea wrapping it does (again, so it doesn't break the apps that have it)?

**Comment by JangoSteve** [comment]
Cool, I thought you were talking about something different with beta10, that broke when you included the new remotipart.

**Comment by gucki** [comment]
@ajrkerr I can confirm it's working now. I like the suggestion of @JangoSteve: leave the helper in but make it return the block without any modifications.

BTW: What are the benefits of using iFrameTransport instead of jquery.form (besides the much smaller code size)? :)

**Comment by JangoSteve** [comment]
@gucki, that's basically it, the much smaller code size. Form.js has a lot of other functionality beyond ajax file uploads, which we're not using. Form.js also adds a lot to the jquery function namespace (which is it's strength if you're actively using it, but a weakness if you're just using it behind the scenes as a dependency).

Now @ajrkerr included in this pull request a bunch of other really nice stuff like the rack middleware and whatnot that eliminate the need for the `remotipart_response` block, which should now allow you to return responses straight from your controller like this:

```
respond_to do |format|
  format.js { render :json => @my_object }
end
```

This is probably my favorite part of this pull request, as it gives remotipart much better rails integration, though it could have been done using form.js as well.

**Comment by ajrkerr** [comment]
@JangoSteve Done.

@gucki I'm partial to the iFrameTransport mostly because of the smaller size, it makes it easier to maintain and modify.  It is also more transparent to jQuery through the use of ajaxTransport and ajaxPrefilter.  Using those, plus another form element and rack middleware, it is possible to send an "HttpAccepts" header with the request, so you can request JSON or another data types back and both jQuery and Rails will think it's a standard XHR request.

**Comment by gucki** [comment]
Thanks for the explaination and good work :). It seems to be working fine here now, so form my side it's a: please pull and release an updated gem :-)

**Comment by JangoSteve** [comment]
Cool, I'm hoping to get to this this week.

@ajrkerr, one more thing. Could you squash 2213bf0 through 8ceec8a into one clean commit?

**Comment by ajrkerr** [comment]
@JangoSteve Done.  I also removed the view-helper section in the readme.

**Comment by gucki** [comment]
Just to let you know: it works in ie8 too :)

**Comment by JangoSteve** [comment]
Almost there. I finally got around to writing an integration test suite for the Rails 3.1 ajax stuff, [here it is](https://github.com/JangoSteve/Rails-jQuery-Demo/commit/fbae57ecf4cbd1e89b6fab8140e35875ce2c3ffa). And more importantly for this issue, I also created an integration spec for the remotipart upload stuff [here](https://github.com/JangoSteve/Rails-jQuery-Demo/commit/1e5570b5d5767ecbe8a7cba94d05becd634d62cf).

**Comment by gucki** [comment]
@JangoSteveAny news on this? Can I help with anything? :)

**Comment by gucki** [comment]
any news here? :)

**Comment by JangoSteve** [comment]
Hey sorry man, it's been a really insane couple weeks. I gotta pull a couple things into jquery-ujs in the morning and then I'll try to finish getting this pulled in.

**Comment by gucki** [comment]
Sorry, but this is so great that I cannot await it _g_

**Comment by JangoSteve** [comment]
Alrighty, I finally got a chance to read through all the changes, and then run this through the test suite on the demo app on Firefox, and almost everything checks out.

I was a little hesitant at first to pull in all the changes made to remotipart.js, because there are a lot of changes that are unrelated to the task at hand. In fact, I see a few things that will break existing applications (like the removal of the `ajax:remotipartSubmit` event hook). However, using the transport does allow us to clean up a lot of the hacking we were doing in the request, and I like that a lot of the now-unnecessary hacking was cleaned up.

So, once I get to the office and can test everything in IE, I'm going to pull this in (don't make any more changes to the pull request), but then I'm going to rewrite a bit of the remotipart.js file, because I think the new transport actually lends itself to a simpler structure for the JS bindings and whatnot.

Everything else looks awesome, I especially like the middleware stuff added. Thanks for all your hard work!

**Comment by JangoSteve** [comment]
I finally got the time to finish working on this and getting all the specs passing and compatible with Rails 3.0 (there were a few issues, but all fixed now).

These changes can be found in the latest release, v1.0.

On a related note, remotipart is now being maintained at https://github.com/JangoSteve/remotipart, so that is where you'll be able to see the latest changes and whatnot.

Thanks again for all your help.

**Comment by gucki** [comment]
Great to hear, thank a lot. I'll give it a try in a couple of days.... :)

**Pull request closed without merging**
